# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      # Install pixi
      - curl -fsSL https://pixi.sh/install.sh | bash
    post_install:
      # Use pixi with full path to install dependencies
      - $HOME/.pixi/bin/pixi --version
      - $HOME/.pixi/bin/pixi install --environment docs
      # Install the package in editable mode using pixi
      - $HOME/.pixi/bin/pixi run --environment docs pip install -e .
      # Install docs dependencies in the RTD Python environment too
      - pip install erdantic versioningit sphinx_rtd_theme sphinxcontrib-mermaid types-pyyaml h5py numpy matplotlib

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
