# load information from setup.cfg/setup.py
{% set data = load_setup_py_data() %}
{% set license = data.get('license') %}
{% set description = data.get('description') %}
{% set url = data.get('url') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: snapred
  version: {{ version_number }}

source:
  path: ..
#  git_url: https://github.com/neutrons/SNAPRed.git
#  git_tag: v0.0.1

build:
  noarch: python
  linux-64: python
  number: {{ build_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
#  script: python setup.py install

requirements:
  host:
    - python
    - versioningit
    - pydantic>=2.7.3,<3

  build:
    - setuptools
    - versioningit
    - {{ pin_compatible("pydantic", min_pin="2.7.3", max_pin="3") }}
    - mantidworkbench
    - qtpy
    - pytest

  run:
    - {{ pin_compatible("pydantic", min_pin="2.7.3", max_pin="3") }}
    - mantidworkbench

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL
  license_file: ../LICENSE
  summary: {{ description }}
