# load information from setup.cfg/setup.py
{% set data = load_setup_py_data() %}
{% set license = data.get('license') %}
{% set description = data.get('description') %}
{% set url = data.get('url') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: SNAPRed
  version:  {{ version_number }}

source:
  git_url: https://github.com/neutrons/SNAPRed.git
  git_tag: v0.0.1

build:
  number:  {{ version_number }}
  string: py{{py}}
  script: python setup.py install
  features:
    - versioning

requirements:
  build:
    - python=3.8
    - setuptools
    - versioningit

  run:
    - python=3.8
    - pydantic
    - mantidworkbench
    - qtpy

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL
  license_file: ../LICENSE
  summary: {{ description }}
