name: docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.41.4
          manifest-path: pyproject.toml
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get install -y graphviz
      - name: Build documentation
        run: |
          pixi run --environment docs build-docs
      - name: Check for warnings and errors
        run: |
          # Ensure build completed without warnings or errors
          BUILD_OUTPUT=$(pixi run --environment docs build-docs 2>&1)
          if echo "$BUILD_OUTPUT" | grep -i "warning\|error\|failed"; then
            echo "Documentation build contains warnings or errors:"
            echo "$BUILD_OUTPUT" | grep -i "warning\|error\|failed"
            exit 1
          else
            echo "Documentation build completed without warnings or errors"
          fi
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/
          retention-days: 30
