name: unit-test

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  LOCKFILE_APPROVED: false

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  lockfile-check:
    runs-on: ubuntu-latest
    outputs:
      lockfile_approved: ${{ steps.check.outputs.lockfile_approved }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH_NAME }}
      - name: Check if bot already committed
        id: check
        run: |
          if git log --pretty=format:"%s" | grep -q "BOT: regenerate pixi.lock"; then
            echo "Already modified. Skipping..."
            echo "lockfile_approved=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile_approved=false" >> $GITHUB_OUTPUT
  linux:
    runs-on: ubuntu-latest
    needs: lockfile-check
    if: ${{ needs.lockfile-check.outputs.lockfile_approved == 'true' || github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ env.BRANCH_NAME }}
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.41.4
          manifest-path: pyproject.toml
      - name: Apt install deps
        run: |
          sudo apt update
          sudo apt-get install xvfb
      - name: Start xvfb daemon
        run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
      - name: run unit tests
        run: |
          echo "running unit tests"
          xvfb-run --server-args="-screen 0 1280x1024x16" -a pixi run test
      - name: List coverage files (debug)
        run: |
          echo "Coverage files generated:"
          ls -la coverage.xml || echo "No coverage.xml found"
          ls -la .coverage || echo "No .coverage found"
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
  integration-tests:
    runs-on: ubuntu-latest
    needs: lockfile-check
    if: ${{ needs.lockfile-check.outputs.lockfile_approved == 'true' || github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
        fetch-depth: 0
        fetch-tags: true
        ref: ${{ env.BRANCH_NAME }}
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.41.4
        manifest-path: pyproject.toml
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt-get install -y xvfb
    - name: Test with pytest
      run: |
        env=tests/resources/integration_test xvfb-run --server-args="-screen 0 1280x1024x16" -a pixi run test-integration
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      if: github.actor != 'dependabot[bot]'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: integration
  gui-tests:
    runs-on: ubuntu-latest
    needs: lockfile-check
    if: ${{ needs.lockfile-check.outputs.lockfile_approved == 'true' || github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
          pixi-version: v0.41.4
          manifest-path: pyproject.toml
          ref: ${{ env.BRANCH_NAME }}
    - name: Apt install deps
      run: |
        sudo apt update
        sudo apt-get install xvfb
    - name: Start xvfb daemon
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
    - name: Gui tests
      run: |
        env=tests/resources/headcheck.yml xvfb-run --server-args="-screen 0 1280x1024x16" --auto-servernum pixi run snapred --headcheck
